apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: port-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: port-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: port-device-plugin-ds
    spec:
      hostNetwork: true
      containers:
      - image: port-device-plugin:v0.1.0
        name: port-device-plugin
        args: [""]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
